[package]
name = "linea"
version = "0.3.1"
authors = ["M Farkas-Dyck <strake888@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Linear Algebra: Vectors and Matrices"
repository = "https://github.com/strake/linea.rs"
documentation = "http://rustdoc.strake.me.uk/linea/index.html"

[dependencies]
typenum = { version = "1.3.*", features = ["no_std"] }
generic-array = { version = "0.2.*", features = ["no_std"] }
glium = { version = "0.13.*", optional = true }
