[package]
name = "linea"
version = "0.1.0"
authors = ["M Farkas-Dyck <strake888@gmail.com>"]

[dependencies]
typenum = { version = "1.3.*", features = ["no_std"] }
generic-array = { version = "0.2.*", features = ["no_std"] }
