[package]
name = "linea"
version = "0.1.0"
authors = ["M Farkas-Dyck <strake888@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Linear Algebra: Vectors and Matrices"

[dependencies]
typenum = { version = "1.3.*", features = ["no_std"] }
generic-array = { version = "0.2.*", features = ["no_std"] }
